import type { Metadata } from 'next'
import './globals.css'
import { Inter } from 'next/font/google'
import { Footer } from '@/components/common/footer'
import { Header } from '@/components/common/header'
import { SessionAuthProvider } from '@/context/session-auth-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Offcorss',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>OFFCORS</title>
      </head>
      <body className={inter.className}>
        <SessionAuthProvider>
          <section className="relative min-h-screen w-full">
            <div className='w-full min-h-[calc(100vh-2.75rem)]'>
              <Header />
              {children}
            </div>
            <Footer />
            {/* <div
            style={{
              clipPath: 'polygon(0 0, 80% 0%, 50% 100%, 0 100%)',
              zIndex: -1
            }} className="absolute top-0 left-0 w-full h-full bg-[#FFDD00]" /> */}
          </section>
        </SessionAuthProvider>
      </body>
    </html>
  )
}
