import type { Metadata } from 'next'
import './globals.css'
import { Inter } from 'next/font/google'
import { Header } from '@/components/common/header'
import { Footer } from '@/components/common/footer'
import { SessionAuthProvider } from '@/context/session-auth-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>OFFCORS</title>
      </head>
      <body className={inter.className}>
        <section className="relative min-h-screen w-full flex flex-col items-center justify-between">
          <SessionAuthProvider>
            <div className='w-full h-full'>
              <Header />
              {children}
            </div>
            <Footer />
          </SessionAuthProvider>
          {/* <div
            style={{
              clipPath: 'polygon(0 0, 80% 0%, 50% 100%, 0 100%)',
              zIndex: -1
            }} className="absolute top-0 left-0 w-full h-full bg-[#FFDD00]" /> */}
        </section>
      </body>
    </html>
  )
}
